//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviewer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int FeedBackId { get; set; }
        public string Advantage { get; set; }
        public string Disavantage { get; set; }
        public string Opinion { get; set; }
    
        public virtual FeedBack FeedBack { get; set; }
        public virtual Reviewer Reviewer1 { get; set; }
        public virtual Reviewer Reviewer2 { get; set; }
    }
}
